apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.env.APP_NAME }}-hpa
  namespace: {{ .Values.env.NAMESPACE }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.env.APP_NAME }}-deploy
  minReplicas: {{ .Values.env.REPLICAS }}
  maxReplicas: {{ .Values.env.MAX_REPLICAS }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
