{{- if not .Values.openshift.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name | default (printf "%s-ingress" .Values.env.APP_NAME) }}
  namespace: {{ .Values.env.NAMESPACE }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.env.APP_HOSTNAME }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.env.APP_HOSTNAME }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env.APP_NAME }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
