apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.env.NAMESPACE }}-limits
  namespace: {{ .Values.env.NAMESPACE }}
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
