apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.env.NAMESPACE }}-quota
  namespace: {{ .Values.env.NAMESPACE }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    persistentvolumeclaims: "5"
    services: "10"
    configmaps: "10"
    secrets: "10"
