apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.APP_NAME }}-service
  namespace: {{ .Values.env.NAMESPACE }}
  labels:
    app: {{ .Values.env.APP_NAME }}
spec:
    type: NodePort
    selector:
        app: {{ .Values.env.APP_NAME }}
    ports:
     - protocol: TCP
       port: {{ .Values.service.port }}
       targetPort: {{ .Values.service.port }}
       nodePort: {{ .Values.service.node_port }}
