apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sandy
  name: sandy
  namespace: test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sandy
