env:
  APP_VERSION: "v25"
  NAME: "Folks"
  REPLICAS: 3
  IMAGE_REGISTRY: "docker.io"
  NAMESPACE: "sd-demo"
  APP_NAME: "app"
  # Hostnames for different access methods
  ROUTE_HOSTNAME: "sd-demo-route-application.io"    # OpenShift Route hostname (HTTPS)
  INGRESS_HOSTNAME: "sd-demo-ingress-application.io"  # Kubernetes Ingress hostname (HTTP)
  APP_HOSTNAME: "sd-demo-route-application.io"    # Default application hostname (same as ROUTE_HOSTNAME)
  MAX_REPLICAS: 10

service:
  port: 3000
  node_port: 30080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3

# Ingress Configuration
ingress:
  enabled: true
  name: "sd-demo-ingress"

# OpenShift specific configuration
openshift:
  enabled: true  # Set to true when deploying on OpenShift

# OpenShift Console Link Configuration
console:
  text: "Demo Application - OpenShift"
  section: "Demo Application SD"
  imageURL: "https://{{ .env.ROUTE_HOSTNAME }}/sd-logo.png"
