name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine version number
        id: version
        run: |
          CURRENT_VERSION=$(grep 'APP_VERSION:' helm/values.yaml | awk '{print $2}')
          if [ -z "$CURRENT_VERSION" ]; then
            NEW_VERSION="v1"
          else
            CURRENT_VERSION_NUMBER=$(echo $CURRENT_VERSION | sed 's/v//')
            NEW_VERSION_NUMBER=$((CURRENT_VERSION_NUMBER + 1))
            NEW_VERSION="v${NEW_VERSION_NUMBER}"
          fi
          echo "::set-output name=version::$NEW_VERSION"

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          docker build -t $IMAGE_TAG .
          echo $IMAGE_TAG >> image_tag.txt

      - name: Push Docker image
        run: |
          docker push $(cat image_tag.txt)

      - name: Set environment variable
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "APP_VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Update values.yaml
        run: |
          cd helm
          sed -i "s|APP_VERSION:.*|APP_VERSION: '${{ env.APP_VERSION }}'|" values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push

