name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        id: build
        run: |
          # Increment revision number
          REV=$(($(git rev-list --count main) + 1))
          IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v${REV}
          docker build -t $IMAGE_TAG .
          echo $IMAGE_TAG >> image_tag.txt

      - name: Set environment variable
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          # Extract version number from IMAGE_TAG
          APP_VERSION=$(echo $IMAGE_TAG | grep -oP '(?<=:v)\d+')
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_TAG }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i "s|APP_VERSION:.*|APP_VERSION: 'v${{ env.APP_VERSION }}'|" values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push

