name: CD

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKERHUB_KEY: ${{ secrets.DOCKER_KEY }}
  IMAGE_NAME: app-helm

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_KEY }}

      - name: Build Docker image
        id: build
        run: |
          # Get current version from values.yaml
          CURRENT_VERSION=$(grep 'APP_VERSION:' helm/values.yaml | awk '{print $2}')
          # Extract version number without 'v'
          CURRENT_VERSION_NUMBER=$(echo $CURRENT_VERSION | sed 's/v//')
          # Increment version number
          NEW_VERSION_NUMBER=$((CURRENT_VERSION_NUMBER + 1))
          NEW_VERSION="v${NEW_VERSION_NUMBER}"
          IMAGE_TAG=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${NEW_VERSION}
          docker build -t $IMAGE_TAG .
          echo $IMAGE_TAG >> image_tag.txt

      - name: Set environment variable
        run: |
          IMAGE_TAG=$(cat image_tag.txt)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "APP_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_TAG }}

      - name: Update values.yaml
        run: |
          cd helm
          sed -i "s|APP_VERSION:.*|APP_VERSION: \"${{ env.APP_VERSION }}\"|" values.yaml
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push

